# Generated by Django 3.2.13 on 2022-07-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='affected_from',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='firstname_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='firstname_name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='last_name'),
        ),
    ]
