# Generated by Django 3.2.13 on 2022-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220719_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='affected_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='joining_date',
            field=models.DateTimeField(null=True),
        ),
    ]
