# Generated by Django 3.2.13 on 2022-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220719_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='mailing',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
